modality: RGB
seed: 42

data:
  frame_count: 8
  segment_length: 1  # Number of (u, v) pairs in each segment
  _root_gulp_dir: ???
  train_gulp_dir: ${data._root_gulp_dir}/rgb_train
  val_gulp_dir: ${data._root_gulp_dir}/rgb_validation
  test_gulp_dir: ${data._root_gulp_dir}/rgb_test
  worker_count: 8
  pin_memory: yes
  preprocessing:
    # Whether network inputs should be BGR rather than RGB.
    bgr: no
    # Whether to rescale input from [0, 255] to [0, 1].
    rescale: yes
    input_size: 224
    scale_size: 256
    mean: [0.485, 0.456, 0.406]
    std: [0.485, 0.456, 0.406]
  train_augmentation:
    multiscale_crop_scales: [1, 0.875, 0.75, 0.66]
  test_augmentation:
    rescale_size: 256

model:
  type: MTRN
  backbone: resnet50
  pretrained: imagenet
  backbone_dim: 256
  dropout: 0.7
  partial_bn: yes

learning:
  batch_size: 128
  optimizer:
    type: SGD
    momentum: 0.9
    weight_decay: 5e-4
  lr: 0.01
  lr_scheduler:
    type: StepLR
    gamma: 0.1
    epochs: [20, 40]

# We can't log the graph for TRN as it is stochastic and causes the JIT tracer to fail
log_graph: False

trainer:
  gradient_clip_val: 20
  max_epochs: 80

  # Write metrics to tensorboard logs every X iterations
  log_every_n_steps: 5
  flush_logs_every_n_steps: 20
  weights_summary: full
  benchmark: yes
  accelerator: dp
  # Assuming V100s for batch size
  gpus: 4


defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
